import "./globals.css";
import Header from "@/components/Shared/Header";
import Navbar from "@/components/Shared/Navbar";
import Footer from "@/components/Shared/Footer";
import CopyrightFooter from "@/components/Shared/Copyright-Footer";

export const metadata = {
  title: "LWS Cart",
  description: "Idea Generated by LWS",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="/images/favicon.ico"
          type="image/x-icon"
        />
      </head>
      <body>
        <Header />
        <Navbar />
        <div>{children}</div>
        <Footer />
        <CopyrightFooter />
      </body>
    </html>
  );
}
